apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      containers:
        - name: app
          image: nginx
          ports:
            - containerPort: 80
          env:
            - name: DB_URL
              value: postgresql://postgres:postgres@db/flask_db

