apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-rwx
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Mi
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  local:
    path: /data/my-p
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - nserver
